<?php

namespace App;

use App\Events\UserCreated;
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class Admin extends Model implements AuditableContract
{
    use Auditable;

    protected $fillable = [
      'name', 'email'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($admin) {
            event(new UserCreated($admin));
        });
    }

    public function user() {
        return $this->morphOne(User::class, 'person');
    }

    public function getUsernameAttribute() {
        return $this->attributes['email'];
    }

    public function getFullNameAttribute() {
        return $this->attributes['name'];
    }
}
