<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class MemberRole extends Model implements AuditableContract
{
    use Auditable;

    protected $fillable = [
        'name'
    ];

    protected static function boot()
    {

        parent::boot(); // TODO: Change the autogenerated stub
        static::saved(function () {
            Cache::forget('member_role_list');
        });

        static::deleted(function () {
            Cache::forget('member_role_list');
        });
    }

    public function members() {
        return $this->hasMany(Member::class);
    }

    public function scopeNotHead($query) {
        return $query->where('name', '<>', 'Head');
    }

    public static function getHead () {
        return optional(static::whereName('Head')->first())->id;
    }

    public static function getDependency () {
        return optional(static::whereName('Dependency')->first())->id;
    }

    public function getIsHeadAttribute() {
        return $this->attributes['name'] == "Head";
    }

}
