<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class State extends Model
{
    protected static function boot()
    {

        parent::boot(); // TODO: Change the autogenerated stub
        static::saved(function () {
            Cache::forget('state_list');
        });

        static::deleted(function () {
            Cache::forget('state_list');
        });
    }

    public function families () {
        return $this->hasMany(Family::class);
    }
}
